# Generated by Django 3.2.3 on 2021-06-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblLineeLav',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('descrizione_linea', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_linee_lav',
                'managed': False,
            },
        ),
    ]
