# Generated by Django 3.2.3 on 2021-06-29 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0002_tbllineelav'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltempi',
            name='id_linea',
            field=models.ForeignKey(blank=True, db_column='id_linea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioneordini.tbllineelav'),
        ),
    ]
