# Generated by Django 3.2.3 on 2021-07-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0003_tbltempi_id_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltempi',
            name='datatempo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tbltempi',
            name='note',
            field=models.CharField(blank=True, max_length=10485760, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='tbltempi',
            name='orafine',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora Fine'),
        ),
        migrations.AlterField(
            model_name='tbltempi',
            name='orainizio',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora Inizio'),
        ),
        migrations.AlterField(
            model_name='tbltempi',
            name='quantitatemporiparazione',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantità Riparati'),
        ),
    ]
