# Generated by Django 3.2.3 on 2021-08-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0004_auto_20210702_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbloperatori',
            options={'managed': False, 'verbose_name': 'tbloperatori', 'verbose_name_plural': 'tbloperatori'},
        ),
        migrations.AlterModelOptions(
            name='tblxrmecclienti',
            options={'managed': False, 'verbose_name': 'tblxrmecclienti', 'verbose_name_plural': 'tblxrmecclienti'},
        ),
        migrations.AlterField(
            model_name='tbldettaglioordini',
            name='dataconsegna',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbltempi',
            name='datatempo',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
