# Generated by Django 3.2.3 on 2021-08-31 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0005_auto_20210813_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltempi',
            name='idoperatore',
            field=models.ForeignKey(db_column='idoperatore', default=40, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioneordini.tbloperatori'),
            preserve_default=False,
        ),
    ]
