# Generated by Django 3.2.3 on 2022-10-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0008_alter_tbltempimaster_id_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltempimaster',
            name='id_linea',
            field=models.ForeignKey(blank=True, db_column='id_linea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioneordini.tbllineelav'),
        ),
    ]
