# Generated by Django 3.2.3 on 2022-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0009_alter_tbltempimaster_id_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldettaglioordini',
            name='iddettordine',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tbltempimaster',
            name='iddettordine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
