# Generated by Django 3.2.3 on 2022-10-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0010_auto_20221004_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbltempimaster',
            old_name='iddettordine',
            new_name='id_dettordine',
        ),
    ]
