# Generated by Django 3.2.3 on 2022-10-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0011_rename_iddettordine_tbltempimaster_id_dettordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltempimaster',
            name='id_dettordine',
            field=models.ForeignKey(blank=True, db_column='iddettordine', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioneordini.tbldettaglioordini'),
        ),
    ]
