# Generated by Django 3.2.3 on 2022-10-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0012_alter_tbltempimaster_id_dettordine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbltempimaster',
            old_name='id_dettordine',
            new_name='iddettordine',
        ),
    ]
