# Generated by Django 3.2.3 on 2022-10-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0014_alter_tbltempi_idtempomaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbltempimaster',
            name='iddettordine',
        ),
    ]
