# Generated by Django 3.2.3 on 2022-10-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0015_remove_tbltempimaster_iddettordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltempimaster',
            name='iddettordine',
            field=models.ForeignKey(blank=True, db_column='iddettordine', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioneordini.tbldettaglioordini'),
        ),
    ]
