# Generated by Django 3.2.3 on 2022-10-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0016_tbltempimaster_iddettordine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbltempimaster',
            options={'managed': True, 'verbose_name': 'tbltempimaster', 'verbose_name_plural': 'tbltempimaster'},
        ),
        migrations.AlterModelTable(
            name='tbltempimaster',
            table='tbltempimaster',
        ),
    ]
