# Generated by Django 3.2.3 on 2022-10-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0017_auto_20221004_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltempimaster',
            name='completato',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbltempimaster',
            name='inlavoro',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
