# Generated by Django 3.2.3 on 2022-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0018_auto_20221005_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltempimaster',
            name='completato',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tbltempimaster',
            name='inlavoro',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
