# Generated by Django 3.2.3 on 2022-12-10 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0020_alter_tbltempi_idtempomaster'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tbltempi',
            constraint=models.CheckConstraint(check=models.Q(('orainizio__gte', datetime.time(6, 0))), name='check_start_date'),
        ),
    ]
