# Generated by Django 3.2.3 on 2022-12-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0021_tbltempi_check_start_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tbltempi',
            name='check_start_date',
        ),
    ]
