# Generated by Django 3.2.3 on 2023-01-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0021_tblclienti_visualizza_come'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcomponenti',
            name='tipo_statore',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
