# Generated by Django 3.2.3 on 2023-02-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0022_tblcomponenti_tipo_statore'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltempimaster',
            name='note',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
