# Generated by Django 3.2.3 on 2023-02-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0023_tbltempimaster_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbltempimaster',
            old_name='note',
            new_name='note_da_linea',
        ),
        migrations.AddField(
            model_name='tbltempimaster',
            name='note_da_ufficio',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
