# Generated by Django 3.2.3 on 2023-07-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0024_auto_20230212_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcomponenti',
            name='perc_tempo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbltempimaster',
            name='note_tempo_nc',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='tbltempimaster',
            name='tempo_conforme',
            field=models.CharField(choices=[('Tempo OK', 'Tempo OK'), ('Tempo Non Conforme', 'Tempo Non Conforme'), ('Non Conformità Gestita', 'Non Conformità Gestita')], default='Tempo OK', max_length=50),
        ),
    ]
