# Generated by Django 3.2.3 on 2023-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0026_remove_tblcomponenti_tempolavorazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcomponenti',
            name='tempolavorazione',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
