# Generated by Django 3.2.3 on 2023-07-08 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0028_auto_20230708_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcollegamenti',
            name='minuti_medi_lavorazione',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='tblcollegamenti',
            name='ore_medie_lavorazione',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='tblcollegamenti',
            name='perc_tempo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblcollegamenti',
            name='secondi_medi_lavorazione',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
