# Generated by Django 3.2.3 on 2021-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qryoperatoriattivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operatore', models.IntegerField(blank=True, null=True)),
                ('cognome', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('idfase', models.IntegerField(blank=True, null=True)),
                ('nordine', models.CharField(blank=True, max_length=50, null=True)),
                ('dataordine', models.DateTimeField(blank=True, null=True)),
                ('idcliente', models.IntegerField(blank=True, null=True)),
                ('iddettordine', models.IntegerField(blank=True, null=True)),
                ('ncommessa', models.CharField(blank=True, max_length=50, null=True)),
                ('quantità', models.FloatField(blank=True, null=True)),
                ('orafine', models.DateTimeField(blank=True, null=True)),
                ('idcollegamento', models.IntegerField(blank=True, null=True)),
                ('idcomponente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qryoperatoriattivi',
                'managed': False,
            },
        ),
    ]
