# Generated by Django 3.2.3 on 2021-07-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0004_auto_20210702_1855'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='tblxrmecclienti',
        #     name='id',
        # ),
        migrations.AlterField(
            model_name='tbldettaglioordini',
            name='dataconsegna',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbloperatori',
            name='idoperatore',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblordini',
            name='idordine',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblpoli',
            name='idpoli',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbltempi',
            name='datatempo',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tbltipocomponenti',
            name='idtipocomponente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblxrmecclienti',
            name='idxrmecclienti',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
