# Generated by Django 3.2.3 on 2021-07-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0006_alter_tblxrmecclienti_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbloperatori',
            name='idoperatore',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblordini',
            name='idordine',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblpoli',
            name='idpoli',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbltipocomponenti',
            name='idtipocomponente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
