# Generated by Django 3.2.3 on 2021-07-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneordini', '0005_auto_20210723_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblxrmecclienti',
            options={'managed': False, 'verbose_name': 'tblxrmecclienti', 'verbose_name_plural': 'tblxrmecclienti'},
        ),
    ]
